name: python-buld

env:
  PROJECT_DIR: python

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python-build.yml'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python-build.yml'

jobs:
  build:
    defaults:
      run:
        working-directory: ./${{ env.PROJECT_DIR }}

    runs-on: ubuntu-latest

    env:
      DB_USER: root
      DB_OLD_PASSWORD: root
      DB_PASSWORD: mysql
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start MYSQL and import DB
      run: |
        sudo systemctl start mysql
        mysqladmin --user=${{ env.DB_USER }} --password=${{ env.DB_OLD_PASSWORD }} version
        mysqladmin --user=${{ env.DB_USER }} --password=${{ env.DB_OLD_PASSWORD }} password ${{ env.DB_PASSWORD }}
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < ${GITHUB_WORKSPACE}/database/initDatabase.sql  

    - name: Install MySQL odbc driver
      run: |
        mkdir odbc_package
        cd odbc_package
        wget https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-ga-debian-x86_64.tar.gz
        tar -xvzf mariadb-connector-odbc-3.1.7-ga-debian-x86_64.tar.gz
        sudo install lib64/libmaodbc.so /usr/lib/
        sudo install -d /usr/lib/mariadb/
        sudo install -d /usr/lib/mariadb/plugin/
        sudo install lib/mariadb/plugin/auth_gssapi_client.so /usr/lib/mariadb/plugin/
        sudo install lib/mariadb/plugin/caching_sha2_password.so /usr/lib/mariadb/plugin/
        sudo install lib/mariadb/plugin/client_ed25519.so /usr/lib/mariadb/plugin/
        sudo install lib/mariadb/plugin/dialog.so /usr/lib/mariadb/plugin/
        sudo install lib/mariadb/plugin/mysql_clear_password.so /usr/lib/mariadb/plugin/
        sudo install lib/mariadb/plugin/sha256_password.so /usr/lib/mariadb/plugin/

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'

    - name: Set up dependencies
      run: pip install -r requirements.txt

    - name: Test
      run: PYTHONPATH=src python -m pytest
 
